### ISSUE TITLE
Notation de l'écoconception

### ISSUE THREAD

**Issue by mjeammet** [betagouv/dashlord#118]
Bonjour, 

Cela fait quelques forum beta qu'on parle d'écoconception, notamment avec Anne-So et je me demandais si Dashlord avait un indicateur de l'écoconception des pages des SE. 

Quelques idées en vrac : 
- dans l'onglet  "performance" de chaque SE il y a 4 paramètres dont 3 sont déjà présents dans le tableau principal mais pas les "bonnes pratiques", qui s'accompagnent d'une mesure du poids de la page. Est-ce qu'on veut en faire un critère supplémentaire sur le tableau ? 
- automatiser quelques vérifications des critères du référentiel général d'écoconception https://ecoresponsable.numerique.gouv.fr/publications/referentiel-general-ecoconception/
- https://www.websitecarbon.com pour calculer le poids des pages d'une manière un peu différente que lighthouse. J'ai l'impression que chacun de ces sites a une manière différente de calculer (avec des poids du simple au double en fonction des méthodes) 
- enquête sur l'écoconception de nos partenaires principaux (notamment Scalingo, on en parlait)

Au plaisir de s'en reparler !

**Comment by revolunet** [comment]
Bonjour, j'avais loupé cette issue; Nous avons ajouté le calcul de l'ecoindex sur la page d'accueil avec cette méthode : https://www.ecoindex.fr/comment-ca-marche/

**Comment by revolunet** [comment]
c'est bon pour toi @mjeammet ? (colonne eco-index) : https://dashlord.incubateur.net/

**Comment by mjeammet** [comment]
Oh, trop bien, merci ! Je vais jeter un oeil à la méthode de calcul et ce qui est pris en compte mais ça a l'air de correspondre à ce que j'avais en tête, merci @revolunet !
