### ISSUE TITLE
Inscription Dahlord SE MISTRAL PENAL

### ISSUE THREAD

**Issue by graphein13** [betagouv/dashlord#141]
Bonjour, 

Est il possible d'inscrire la SE MISTRAL PENAL sur Dashlord ? nous n'avons pas d'URL publique, nous sommes sur l'intranet justice,

Quelle est la procédure à suivre ?

https://mistral-dev.nantes.preprod.ioc.intranet.justice.gouv.fr/

https://beta.gouv.fr/startups/T2BJustice.html

Je vous remercie, 

Maxime GAMMAIRE

**Comment by revolunet** [comment]
Bonjour, si l'appli est sur un réseau privé, le seul moyen d'utiliser dashlord est d'utiliser des runners github dédiés sur ce réseau, lesquels seront capables d'atteindre la cible . A dispo pour en discuter si c'est dans vos projets.
