### ISSUE TITLE
Faux négatifs : pages "Mentions légales", "Politique de confidentialité" et utilisation du DSFR

### ISSUE THREAD

**Issue by RomainRonflette** [betagouv/dashlord#152]
Le dashloard (https://incubateur-territoires.github.io/dashlord/) ne prend pas en compte les pages "Mentions légales" et "Politique de confidentialité" pour la plateforme **Toutes et tous connecté·e·s** (https://tous-connectes.anct.gouv.fr/), ainsi que l'utilisation du DSFR (portage sur Angular par l'équipe de la plateforme https://github.com/betagouv/ngx-dsfr).

- Page "Politique de confidentialité" : https://tous-connectes.anct.gouv.fr/donnees-personnelles
- Page "Mentions légales" : https://tous-connectes.anct.gouv.fr/mentions-legales

**Comment by revolunet** [comment]
Ok merci du retour on va corriger ça

**Comment by revolunet** [comment]
Si tu relances les scan de ton URL sur ton dashlord ce devrait être bon
