### ISSUE TITLE
Mots manquants : pages "Mentions légales", "Politique de confidentialité" 

### ISSUE THREAD

**Issue by abdelazizsakhi** [betagouv/dashlord#158]
Le dashlord nous indique des mots manquants sur les pages suivantes : 

- Page "Politique de confidentialité" : https://tous-connectes.anct.gouv.fr/donnees-personnelles
- Page "Mentions légales" : https://tous-connectes.anct.gouv.fr/mentions-legales

Or les mots sont bien présents dans ces pages. C'est peut être lié à la casse des mots dans le corps des pages.

**Comment by revolunet** [comment]
Merci du retour on corrige rapidement

**Comment by revolunet** [comment]
Ok c'est le même souci que [précédemment](https://github.com/betagouv/dashlord/issues/152), j'ai release une nouvelle version et le problème devrait être résolu au prochain run.

**Comment by revolunet** [comment]
fixed
