### ISSUE TITLE
Ajouter des liens d'évitement

### ISSUE THREAD

**Issue by astranchet** [betagouv/dashlord#161]
Indispensable pour une navigation au clavier efficace, et très peu couteux
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/lien-d-evitement/

**Comment by revolunet** [comment]
pour la page détail d'une URL pour naviguer d'onglet en onglet ?

**Comment by astranchet** [comment]
Ces liens sont des ancres, ils servent à naviguer plus facilement au clavier pour accéder à des zones précises de la page (par exemple, si tu veux accéder au footer là, tu dois tabuler sur toutes les cases du tableau avant).

Ils doivent être présent sur toutes les pages (comme le header et le footer en fait)

**Comment by astranchet** [comment]
Il y a un petit bug graphique sur ce composant (qui devrait coller le haut de l'écran). Ce n'est pas 100 % DSFR compliant du coup, mais en terme d'accessibilité, le job is done. 

<img width="1468" alt="Capture d’écran 2024-03-12 à 14 30 44" src="https://github.com/betagouv/dashlord/assets/1374389/74c494de-112c-4e45-bb4e-af8d80d62df8">
<img width="1468" alt="Capture d’écran 2024-03-12 à 14 30 57" src="https://github.com/betagouv/dashlord/assets/1374389/eb212698-41f0-468e-a2c6-dad79eac3cb8">

Je te laisse choisir si on clotûre ou pas.

**Comment by revolunet** [comment]
a priori c'est corrigé... une classe qui trainait :) https://dashlord.incubateur.net/
