### ISSUE TITLE
Enlever le focus sur les éléments non clicables 

### ISSUE THREAD

**Issue by astranchet** [betagouv/dashlord#162]
En naviguant au clavier, certains éléments sont focusables mais pas activables

<img width="1241" alt="Capture d’écran 2024-02-15 à 09 08 25" src="https://github.com/betagouv/dashlord/assets/1374389/4c3f2380-4a94-41ea-983f-de43da83052c">

**Comment by revolunet** [comment]
Alors je n'ai pas d'explication mais visiblement c'est un comportement normal sur des "Tabs" ? 

j'ai la meme chose ici : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/onglet

**Comment by astranchet** [comment]
Bien vu effectivement 🤔. Je vais poser la question au DSFR et je close cette issue
