### ISSUE TITLE
Marquer chaque page avec un h1

### ISSUE THREAD

**Issue by astranchet** [betagouv/dashlord#163]
Sur les fiches produits, il manque un h1 (ici, ça devrait être l'URL à priori)

Les headings suivant devraient être des h2

<img width="1470" alt="Capture d’écran 2024-02-15 à 09 09 49" src="https://github.com/betagouv/dashlord/assets/1374389/2aa5cd3d-f980-48e2-87d3-3a7405e005d9">

**Comment by revolunet** [comment]
fixed in https://github.com/SocialGouv/dashlord-actions/pull/304

**Comment by astranchet** [comment]
Quelques autres exemples de pages sans h1 : 
- https://dashlord.incubateur.net/ (ça pourrait être "Tableau de bord")
- https://dashlord.incubateur.net/category/ademe/ (ça pourraît être "Tableau de bord de l'ADEME")
- https://dashlord.incubateur.net/tag/agriculture/ (ça pourrait être "Tableau de bord : Agriculture" ?)
- https://dashlord.incubateur.net/startup/acceslibre/ ("Accèslibre")

**Comment by revolunet** [comment]
J'ai publié de nouveaux correctifs sur https://dashlord.incubateur.net, ré-ouvres s'il manque (encore) des points merci!
