### ISSUE TITLE
Dashlord n'est pas à jour

### ISSUE THREAD

**Issue by K4ST0R** [betagouv/dashlord#173]
Bonjour,

Suite à ma pull request : https://github.com/betagouv/dashlord/pull/172, je constate que Dashlord n'a pas été mise à jour. S'agit il d'un problème de votre côté ?

Merci beaucoup!

**Comment by revolunet** [comment]
Bonjour @K4ST0R, le robot tourne le dimanche, tu devrais voir ton URL apparaitre lundi prochain

**Comment by revolunet** [comment]
good ?

**Comment by K4ST0R** [comment]
Oui, merci beaucoup!
