### ISSUE TITLE
Ajout du projet EnvErgo sur Dashlord

### ISSUE THREAD

**Issue by thibault** [betagouv/dashlord#174]
Hello l'équipe,

Est-il possible d'ajouter le projet EnvErgo sur Dashlord ?

L'url est : https://envergo.beta.gouv.fr

À votre disposition si vous avez besoin d'infos ou d'actions de notre part.

Merci.

**Comment by revolunet** [comment]
EnvErgo est déjà sur le dashlord du MTES : https://mtes-mct.github.io/dashlord/startup/envergo

(et il est indiqué sur leur fiche aussi)
