### ISSUE TITLE
déclaration de l'application précontentieux

### ISSUE THREAD

**Issue by OpenActu** [betagouv/dashlord#184]
Bonjour, 

Est-il possible d'ajouter l'application précontentieux dans le dashlord (https://espace-membre.incubateur.net/startups/precontentieux.justice)

La configuration est la suivante : 
  - url: https://dev.precontentieux.app.cc.anje-justice.fr/
    category: justice
    betaId: precontentieux

D'avance merci

**Comment by revolunet** [comment]
Bonjour, cette URL a bien été intégrée

https://dashlord.incubateur.net/url/dev-precontentieux-app-cc-anje-justice-fr/

Cordialement
