### ISSUE TITLE
Faux positif de secret AWS dans les rapports, ce qui empéche le push de mise à jour sur le repo

### ISSUE THREAD

**Issue by jdauphant** [betagouv/dashlord#188]
Un secret AWS est trouvé dans les rapports des 2 dernières semaines (ça doit surement être un faux positif).
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/ff8356a5-d4ab-4f75-b094-9c9fe14455e1">

**Comment by revolunet** [comment]
ok apres enquete j'ai eu confirmation que c'est un faux positif...

**Comment by revolunet** [comment]
fixed
